---
abstract: 'Virtual net personality, Hidek, age 40'
author:
  - 'Goro Fuji (gfx) <gfuji(at)cpan.org>'
build_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
  ExtUtils::ParseXS: 2.21
  Test::More: 0.88
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Acme::Hidek
name: Acme-Hidek
no_index:
  directory:
    - example
    - inc
    - t
    - xt
requires:
  Mouse: 0
  Time::Piece: 0
  XSLoader: 0.02
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/gfx/p5-Acme-Hidek.git
version: 41.0
